import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import productsRouter from "./products";
import entitiesRouter from "./entities";
import invoicesRouter from "./invoices";
import purchasesRouter from "./purchases";
import paymentsRouter from "./payments";
import rewardsRouter from "./rewards";
import manufacturingRouter from "./manufacturing";
import dashboardRouter from "./dashboard";
import accountsRouter from "./accounts";
import workersRouter from "./workers";
import expensesRouter from "./expenses";
import customerOrdersRouter from "./customer-orders";
import reportsRouter from "./reports";
import subscriptionsRouter from "./subscriptions";
import settingsRouter from "./settings";
import gstinRouter from "./gstin";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(productsRouter);
router.use(entitiesRouter);
router.use(invoicesRouter);
router.use(purchasesRouter);
router.use(paymentsRouter);
router.use(rewardsRouter);
router.use(manufacturingRouter);
router.use(dashboardRouter);
router.use(accountsRouter);
router.use(workersRouter);
router.use(expensesRouter);
router.use(customerOrdersRouter);
router.use(reportsRouter);
router.use(subscriptionsRouter);
router.use(settingsRouter);
router.use(gstinRouter);

export default router;
